# Generated by Django 5.1.4 on 2024-12-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_input", models.TextField()),
                ("bot_response", models.TextField()),
                ("mood", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MoodText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeStamp", models.DateTimeField(unique=True)),
                ("mood", models.CharField(max_length=50)),
            ],
        ),
    ]
