# Generated by Django 5.1.4 on 2024-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatlog",
            name="timestamp",
            field=models.DateTimeField(unique=True),
        ),
    ]
