# Generated by Django 4.2.17 on 2024-12-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("depression_recovery", "0002_alter_chatlog_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorData",
            fields=[
                ("doctorId", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="MoodVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("mood", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PatientData",
            fields=[
                ("patientId", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="WeablesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("respiration_rate", models.FloatField()),
                ("body_temperature", models.FloatField()),
                ("blood_oxygen", models.FloatField()),
                ("eye_movement", models.FloatField()),
                ("sleeping_hours", models.FloatField()),
                ("stress_level", models.FloatField()),
                ("mood_data", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="MoodText",
        ),
        migrations.AlterField(
            model_name="chatlog",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="chat_logs",
            field=models.ManyToManyField(blank=True, to="depression_recovery.chatlog"),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients_under_care",
                to="depression_recovery.doctordata",
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="video_moods",
            field=models.ManyToManyField(
                blank=True, to="depression_recovery.moodvideo"
            ),
        ),
        migrations.AddField(
            model_name="patientdata",
            name="weables_data",
            field=models.ManyToManyField(
                blank=True, to="depression_recovery.weablesdata"
            ),
        ),
        migrations.AddField(
            model_name="doctordata",
            name="patients",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_doctors",
                to="depression_recovery.patientdata",
            ),
        ),
        migrations.AddField(
            model_name="doctordata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
