# Generated by Django 4.2.17 on 2024-12-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "depression_recovery",
            "0003_doctordata_moodvideo_patientdata_weablesdata_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientdata",
            name="chat_logs",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="video_moods",
        ),
        migrations.RemoveField(
            model_name="patientdata",
            name="weables_data",
        ),
        migrations.AddField(
            model_name="chatlog",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_logs",
                to="depression_recovery.patientdata",
            ),
        ),
        migrations.AddField(
            model_name="moodvideo",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mood_video",
                to="depression_recovery.patientdata",
            ),
        ),
        migrations.AddField(
            model_name="weablesdata",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weables_data",
                to="depression_recovery.patientdata",
            ),
        ),
        migrations.AlterField(
            model_name="patientdata",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients_under_care",
                to="depression_recovery.doctordata",
            ),
        ),
    ]
