# Generated by Django 4.2.17 on 2024-12-18 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0004_remove_patientdata_chat_logs_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weablesdata",
            old_name="eye_movement",
            new_name="heart_rate",
        ),
    ]
