# Generated by Django 4.2.17 on 2024-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0005_rename_eye_movement_weablesdata_heart_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="JoinedTime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="moodvideo",
            name="timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
