# Generated by Django 4.2.17 on 2024-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "depression_recovery",
            "0006_patientdata_joinedtime_alter_moodvideo_timestamp",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
