# Generated by Django 4.2.17 on 2024-12-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0007_patientdata_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctordata",
            name="patients",
        ),
    ]
