# Generated by Django 4.2.17 on 2024-12-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0008_remove_doctordata_patients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weablesdata",
            name="stress_level",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
