# Generated by Django 4.2.17 on 2024-12-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0009_alter_weablesdata_stress_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="BecksIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("score", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="becks_index",
                        to="depression_recovery.patientdata",
                    ),
                ),
            ],
        ),
    ]
