# Generated by Django 4.2.17 on 2024-12-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("depression_recovery", "0011_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientdata",
            name="BeckTest",
            field=models.BooleanField(default=False),
        ),
    ]
